matrix:
  include:
    - script: cd XSB/build && ./configure --with-bits64 && ./makexsb --config-tag=bits64
      language: objective-c
    - script: cd XSB/build && ./configure && ./makexsb
      language: objective-c
    - script: cd XSB/build && ./configure --with-bits64 && ./makexsb --config-tag=bits64 --with-odbc
      language: objective-c
    - script: cd XSB/build && ./configure && ./makexsb --with-odbc
      language: objective-c
    - script: cd XSB/build && ./configure --with-bits64 && ./makexsb --config-tag=bits64
      language: c
    - script: cd XSB/build && ./configure && ./makexsb
      language: c
    - script: cd XSB/build && ./configure --with-bits64 && ./makexsb --config-tag=bits64 --with-odbc
      language: c
    - script: cd XSB/build && ./configure && ./makexsb --with-odbc
      language: c
